csiConfig: 
  - clusterID: "32a09c66-a6c3-4329-8339-15510d2ea9e0"
    monitors:
      - "172.16.10.51:6789"
      - "172.16.10.52:6789" 
      - "172.16.10.53:6789"
    cephFS:
      subvolumeGroup: "csi"
provisioner:
  name: provisioner
  replicaCount: 2

# Disable Helm-managed resources since you're creating them separately
storageClass:
  create: false

secret:
  create: false